version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ../postgres-data:/var/lib/postgresql/data
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/mysite
        ports:
            - 8000:8000
        depends_on:
            - db
    rabbit:
        image: rabbitmq
        depends_on:
            - web
    celery:
        build: .
        volumes:
            - .:/mysite
        command: celery worker --app mysite --loglevel=info
        depends_on:
            - rabbit
    redis:
        image: redis
        depends_on:
            - web
            - celery
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web